### ISSUE TITLE
Crossbows and Bows

### ISSUE THREAD

**Issue by King-Tulip** [KreloX/SpartanFire#1]
Idk if it's just the ice bow and crossbow, but everytime I try to load up an arrow to shoot it, my game always freezes, then crashes. I haven't tried the other bows and crossbows, but the ice ones are the one that always do that. They used to work just fine too so it's weird.

**Comment by KreloX** [comment]
I can't replicate this issue. Presuming you're playing with other mods you can remove them one by one to see if it isn't a conflict.
