### ISSUE TITLE
Spartan: Ice and Fire crash.

### ISSUE THREAD

**Issue by kqxmii** [KreloX/SpartanFire#10]
Hello! Recently I've made my own mod pack, and whenever I launch up Minecraft, I get an error. 

Failure message: Spartan Weaponry: Ice and Fire (swiaf) encountered an error during the load_registries event phase
		java.lang.NullPointerException: null

Is there any fix to this? 
(also, I'm not very experienced with modding so I know almost nothing about mods and mod errors, etc.)

Thanks in advance.

**Comment by KreloX** [comment]
Check if your mods' versions are the latest, if yes then please send the full crash report.

**Comment by KreloX** [comment]
inactive, feel free to reopen later
