### ISSUE TITLE
Weapons with "Iced" Material bonus crash on hit

### ISSUE THREAD

**Issue by Novdalune** [KreloX/SpartanFire#12]
I've tested this on weapons with both Fire and Lightning as well. None of those crash. I've tested weapons with Iced 1 and Iced 2 and they both cause hard crashes

[crash-2022-07-27_19.24.59-server.txt](https://github.com/KreloX/SpartanFire/files/9204340/crash-2022-07-27_19.24.59-server.txt)
.

**Comment by KreloX** [comment]
You must have the latest version of Ice and Fire. You have 2.1.9, while the latest is 2.1.10.
