### ISSUE TITLE
Wrong Rendering Animation (1.16.5)

### ISSUE THREAD

**Issue by Exokyhh** [KreloX/SpartanFire#13]
Forge version: 36.2.34 (1.16.5)
Mod version: SW Ice and Fire-1.16.5-1.1.0

The Javelins from this mod use the Tomahawk animation when charging the attack with right click, while instead it should use the Javelin animations, you can check the picture to understand what i'm saying: 

the first picture of each pair looks how the javelin animations is in the original mod, while the second one shows how it looks in your mod

![2022-09-22_20 51 37](https://user-images.githubusercontent.com/90096585/191828482-7dbadf24-0a07-4d69-a5cc-bf6d7b89b67f.png)
![2022-09-22_20 51 48](https://user-images.githubusercontent.com/90096585/191828492-e0bdd2b5-14ba-472f-96a4-fb159834de67.png)

The javelin renders opposite when in 3rd person, looking like im about to throw a Tomahawk instead of a Javelin

![2022-09-22_20 51 57](https://user-images.githubusercontent.com/90096585/191828494-eaf24943-9dda-45b3-b428-ca69fbf80a93.png)
![2022-09-22_20 52 04](https://user-images.githubusercontent.com/90096585/191828498-40993170-3351-4880-b46e-ce453f14bfad.png)

From a different point of view: 
![2022-09-22_20 52 16](https://user-images.githubusercontent.com/90096585/191828501-590e6939-22e2-4bbe-87fb-26040490e660.png)
![2022-09-22_20 52 26](https://user-images.githubusercontent.com/90096585/191828506-63c38528-5f2d-4085-84a9-56fbd12af084.png)

**Comment by KreloX** [comment]
Thanks for pointing this out, I'll fix it in the next update along with the parrying daggers not having a blocking model.

**Comment by Exokyhh** [comment]
No problem! Just wondering, when will you release the next update? Because I want to start a modpack but im not sure if updating the mod may cause some bugs/problems, so I'd rather wait for it if it's happening soon

**Comment by KreloX** [comment]
The update won't break anything, It'll only change the items' models

**Comment by Exokyhh** [comment]
Oh okay, nice to know!

**Comment by Exokyhh** [comment]
I've just seen I accidentally closed the issue, mb
