### ISSUE TITLE
Iced weapons will crash the game

### ISSUE THREAD

**Issue by LoveRuinsItAll** [KreloX/SpartanFire#15]
I have the latest version of the mod witch is 1.1.0 updated on 4th jully 2022, saying that any ice weapon wouldn't crash the game anymore. Well, I still crash... Do you have any idea if it's coming from the mod or something else I have to update?

**Comment by KreloX** [comment]
It would help if you could send the crash report here

**Comment by KreloX** [comment]
inactive
