### ISSUE TITLE
Spartan Weaponry was updated to 1.18.2 [SUGGESTION]

### ISSUE THREAD

**Issue by GhostLupine** [KreloX/SpartanFire#16]
Hey. So I just found out that Spartan Weaponry has been updated to 1.18.2. Along with that, Ice and Fire are also updated to 1.18.2. So with that information, I would like to ask if there are any plans to update this mod to 1.18.2? It would be really awesome if that happened.

**Comment by KreloX** [comment]
I will definitely update all of my Spartan Weaponry addons to 1.18.2 but it probably won't be soon.
