### ISSUE TITLE
Crash Upon Startup (No other mods installed)

### ISSUE THREAD

**Issue by jimtarrosimbarros** [KreloX/SpartanFire#18]
Forge Version: 47.3.4

![Screenshot 2024-07-04 152129](https://github.com/KreloX/SpartanFire/assets/174750440/0cf74620-70f1-40b3-a542-9fd6a36a76f9)

![Screenshot 2024-07-04 152238](https://github.com/KreloX/SpartanFire/assets/174750440/c9922c34-e16c-4352-a02a-e98ba6abf36c)

[crash-2024-07-04_15.11.30-fml.txt](https://github.com/user-attachments/files/16103185/crash-2024-07-04_15.11.30-fml.txt)

**Comment by omegadmm** [comment]
I got BClib installed in mine and the crash log says BCLib is complaining about a transformer issue.
[crash-2024-07-04_22.00.40-client.txt](https://github.com/user-attachments/files/16104384/crash-2024-07-04_22.00.40-client.txt)

**Comment by KreloX** [comment]
Thanks for reporting this issue, I'm currently looking into it

**Comment by KreloX** [comment]
Fixed in Spartan Weaponry Addon Toolkit 1.2.2
