### ISSUE TITLE
crashed forge:bones/dragon

### ISSUE THREAD

**Issue by gorroii** [KreloX/SpartanFire#19]
![Screenshot_47](https://github.com/KreloX/SpartanFire/assets/166294674/f5a50c93-ead6-477d-ba4d-ef343443cc7b)
![Screenshot_48](https://github.com/KreloX/SpartanFire/assets/166294674/f341abfe-6c81-4a24-8962-bf36eace45c6)

**Comment by KreloX** [comment]
I am currently working on a fix

**Comment by gorroii** [comment]
Also could you reduce damage of dragonsteel battleaxes? Like they have 46 damage that's kinda unbalanced

**Comment by KreloX** [comment]
Fixed in version 2.0.2

**Comment by KreloX** [comment]
Dragonsteel is unbalanced by default, all values are calculated not hard-coded
