### ISSUE TITLE
hitting enemies with spartan weapons crashes the game

### ISSUE THREAD

**Issue by spamsistaken** [KreloX/SpartanFire#2]
Whenever I have spartan weaponry: ice and fire active, if I go swing at any mob it crashes my game. my game versions are forge 1.16.5 36.1.35 and im using spartan weaponry ice and fire 5/20/22 most recent fix and spartan weaponry SpartanWeaponry-1.16.5-2.2.0-rc-2.jar. If i uninstall ice and fire addon the mod works fine. i have no idea what could be causing this

**Comment by KreloX** [comment]
Could you please send me the crash report?

**Comment by KreloX** [comment]
Inactive
