### ISSUE TITLE
Better combat weapon animations not working

### ISSUE THREAD

**Issue by polykatt** [KreloX/SpartanFire#23]
Better combat weapon animations are not working for some weapons. I haven't tested every weapon type but I noticed this issue with the pike and saber.  I am also using the [undergarden](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry-undergarden) version and these issues are also present in that mod.

And a small side issue the swinging sounds for the battleaxe are not consistent with the original spartan weaponry mod (ice & fire and undergarden versions).

Edit: Someone in the comments section mentioned this issue saying that its the saber, javelin, tomahawk, throwing knife and pike that are incompatible with better combat. I would assume these weapons are problematic for the undergarden compat mod as well

**Comment by KreloX** [comment]
Fixed in KreloX/SpartanFire@7c2da233b4519681bf6c7393742999533cd60fbb
