### ISSUE TITLE
Regisrty Error while joining a server

### ISSUE THREAD

**Issue by SikinoGaming** [KreloX/SpartanFire#3]
We are 3 friends in a minecraft forge server hosted by me. When connecting to a server with SWIAF, me and one of my friend can't connect to the server but the second one can connect, the bug is caused by the ``"swaif:dread_stone_stairs"`` that are with corrupted textures for my friend and I in solo world but not for the one who can connect. We have the exact same mod, for the server and our MC instances, same for the forge version.
P.S.: Joined a screenshot of the log when the error happend.

![image](https://user-images.githubusercontent.com/71142041/169863738-f6d4a1b7-9d37-4611-beea-7bfe1cd4ffd2.png)

Hope you can help us !

**Comment by KreloX** [comment]
This is a known issue. Earlier in development I changed the mod's id from "spartanfire" to "swiaf" which helped some people, but apparently not all. Nevertheless, this is [an issue](https://github.com/Alex-the-666/Ice_and_Fire/issues/4446) of the Ice and Fire mod which already has a fix but it's not released yet.
