### ISSUE TITLE
Make weapon damage derive from Ice and Fire config?

### ISSUE THREAD

**Issue by Sazuzaki** [KreloX/SpartanFire#4]
Heyo!

Just wanted to see if it was possible for you to make the config from Ice and Fire influence the damage of the dragonbone and dragonsteel weapons in your mod. 

Thank you!

**Comment by KreloX** [comment]
I don't know why it isn't working right now, I'm using the Ice and Fire's own material definition which already uses the value from config. Nevertheless, I'll be doing my own config file if anything.

**Comment by Sazuzaki** [comment]
Sounds good man, I'll be looking forward to that. Thanks!

**Comment by KreloX** [comment]
Closing this one, maybe I'll do my own config #7
