### ISSUE TITLE
Incompatible with the lastest IAF

### ISSUE THREAD

**Issue by Kasualix** [KreloX/SpartanFire#8]
crash report: https://pastebin.ubuntu.com/p/tWmmmtf7BV/
As IAF updated, the file name "FrozenEntityProperties" has changed to "FrozenProperties".
I just crashed when I attack a monster with an ice dragonsteel weapon.
![image](https://user-images.githubusercontent.com/76616758/177117992-6465edcd-c919-422c-9c41-eef5da786ef3.png)
![image](https://user-images.githubusercontent.com/76616758/177118064-e10c6093-4c08-46c2-a4e7-7ce11142ae9c.png)

Sorry I'm not sure whether or not other file name has changed.

**Comment by KreloX** [comment]
Fixed in version 1.1.0 but curseforge has to approve it first
